### ISSUE TITLE
What happened????

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/HeadScratching#1]
@JPH71

Just testing to see if this is even going to work!  I wonder what happened....do you think that Aiden deleted the repository....or do you think GitHub didn't appreciate the naughty screen caps....or....?

**Comment by JPH71** [comment]
I really don't know, and Aiden does'nt seem to always get the mail's..
I tried it with the original server name and that didn't work...
I am going to put the vbscript back in as backup..
Hope you have a god day

**Comment by CodyBerenson** [comment]
@acvigue hi Auden, what happened???  everything ok?

**Comment by acvigue** [comment]
Don't respond to this. Delete this issue. Please don't include me in further issues. Thank you.

**Comment by JPH71** [comment]
What's going on?
