### ISSUE TITLE
try this

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/HeadScratching#3]
@j-ktz

While we are waiting for Aiden to fix his thumbor instance, I went ahead and created a new one in the Google Cloud.  Go ahead and change your preferences for each of the agents, restart your PMS, and you should be back in business.  

http://35.202.167.229:8888/unsafe

I'm not going to widely advertise this as a solution, but you've been along for the ride from the beginning and you deserve to be in working order.  

If you could reply to let me know that you got this, that would be terrific.

**Comment by j-ktz** [comment]
@CodyBerenson Thanks Cody!!! I'll update my agents and try this. Appreciate you. 🙌

**Comment by CodyBerenson** [comment]
@j-ktz The cloud flaked out on me.  i'm reestablishing the service....will hit you back when it is a go

**Comment by CodyBerenson** [comment]
@j-ktz 
ok, its been a long day fighting with google cloud but i think I have it up, enabled, active and running, and in a state that if it goes down for any reason it will autorestart...

so, use this as the thumbor preference.  Ignore what I gave you earlier. It is up and running...and hopefully I figured out how to keep the IP address persistent.  :)

http://35.232.232.183:8888/unsafe

**Comment by j-ktz** [comment]
Thanks Cody! I’ll give it a try : )

**Comment by CodyBerenson** [comment]
@j-ktz 
Please let me know if this worked for you.  I'd like to delete this thread.  :)

**Comment by j-ktz** [comment]
Just tested one and it did work! Delete. Thanks Cody!!!
